services:
  - type: web
    name: ortometric-api
    env: python
    rootDir: api

    buildCommand: python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --access-logfile - --error-logfile - --log-level debug

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8

      - key: FLASK_ENV
        value: production

      - key: FLASK_DEBUG
        value: "False"

      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        sync: false

      - key: JWT_SECRET_KEY
        sync: false

      - key: FRONTEND_ORIGINS
        value: https://orto-metric-web-inx8.vercel.app

      - key: FRONTEND_ORIGIN_REGEX
        value: https://.*\\.vercel\\.app

      - key: JWT_COOKIE_SAMESITE
        value: None

      - key: JWT_COOKIE_SECURE
        value: "true"