"""Increase password_hash field from 120 to 255 characters

Revision ID: 084151451c58
Revises: 20260404_01
Create Date: 2026-04-05 04:54:22.715033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084151451c58'
down_revision = '20260404_01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_type_preference', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('measurement_type_preference_user_id_key'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('measurement_type_preference', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('measurement_type_preference_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
